INSERT INTO tb_category (name, created_at) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Home & Kitchen', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Gaming', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Baby', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Art & Craft', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Industrial', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Outdoors', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Bags & Luggage', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('DIY & Tools', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Grocery', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Alcohol & Beverages', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Collectibles', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Luxury', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Stationery', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Medical Supplies', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Wearable Tech', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Smart Home', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Video Equipment', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Comics & Manga', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Car Accessories', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Camping & Hiking', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Water Sports', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Cycling', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Winter Sports', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Fishing', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Board Games', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Card Games', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Virtual Reality', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Drones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Survival Gear', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Organic Products', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Handmade Items', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Ethical & Sustainable', NOW());